apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.backend.name }}

spec:
  replicas: {{ .Values.backend.replicaCount }}

  selector:
    matchLabels:
      app: django

  template:
    metadata:
      labels:
        app: django

    spec:
      containers:
        - name: django
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.containerPort }}

          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}

          startupProbe:
            httpGet:
              path: {{ .Values.backend.probes.startup.path }}
              port: {{ .Values.backend.containerPort }}
            initialDelaySeconds: {{ .Values.backend.probes.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.probes.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.probes.startup.timeoutSeconds }}
            failureThreshold: {{ .Values.backend.probes.startup.failureThreshold }}

          readinessProbe:
            httpGet:
              path: {{ .Values.backend.probes.readiness.path }}
              port: {{ .Values.backend.containerPort }}
            initialDelaySeconds: {{ .Values.backend.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.backend.probes.readiness.failureThreshold }}

          livenessProbe:
            httpGet:
              path: {{ .Values.backend.probes.liveness.path }}
              port: {{ .Values.backend.containerPort }}
            initialDelaySeconds: {{ .Values.backend.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.backend.probes.liveness.failureThreshold }}

          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.secret.name }}"
                  key: POSTGRES_DB

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.secret.name }}"
                  key: POSTGRES_USER

            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.secret.name }}"
                  key: POSTGRES_PASSWORD

            - name: DB_HOST
              value: "{{ .Values.postgres.service.name }}"

            - name: DB_PORT
              value: "{{ .Values.postgres.service.port }}"